import { defineType, defineField } from 'sanity'

export const activityType = defineType({
  name: 'activity',
  title: 'Activities / Extras',
  type: 'document',
  groups: [
    { name: 'content', title: '📝 Content' },
    { name: 'pricing', title: '💰 Pricing & Booking' },
  ],
  fields: [
    defineField({
      name: 'name',
      title: 'Activity Name (English)',
      description: 'The display name of the activity or extra.',
      type: 'string',
      validation: (Rule) => Rule.required().error('Name is required.'),
      group: 'content',
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      description: 'URL identifier. Locked to prevent breaking website navigation.',
      type: 'slug',
      options: { source: 'name' },
      readOnly: true,
      validation: (Rule) => Rule.required(),
      group: 'content',
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero Image',
      description: 'Main image for this activity (high-quality landscape format). If removed, the website will use the default image.',
      type: 'image',
      options: { hotspot: true },
      group: 'content',
    }),
    defineField({
      name: 'description',
      title: 'Activity Description (English)',
      description: 'Main descriptive text.',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'content',
    }),
    defineField({
      name: 'description_id',
      title: 'Activity Description (Indonesian)',
      description: 'Deskripsi utama dalam bahasa Indonesia.',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'content',
    }),
    defineField({
      name: 'duration',
      title: 'Duration — English',
      description: 'Example: "Half Day" or "2 hours"',
      type: 'string',
      group: 'content',
    }),
    defineField({
      name: 'duration_id',
      title: 'Duration — Indonesian',
      description: 'Contoh: "Setengah Hari" atau "2 jam"',
      type: 'string',
      group: 'content',
    }),
    defineField({
      name: 'price',
      title: 'Starting Price (IDR)',
      description: 'Example: 150000 (do not include commas or dots).',
      type: 'number',
      group: 'pricing',
    }),
    defineField({
      name: 'triplaExtrasLink',
      title: 'Tripla Add-ons Booking Link',
      description: 'Direct booking link for this specific activity on the Tripla platform.',
      type: 'url',
      group: 'pricing',
    }),
  ],
})
