import { defineType, defineField } from 'sanity'

export const homepageType = defineType({
  name: 'homepage',
  title: 'Homepage',
  type: 'document',
  preview: {
    select: { title: 'heroTitle' },
    prepare({ title }) {
      return {
        title: 'Homepage',
        subtitle: title || 'Edit homepage content',
      }
    },
  },
  groups: [
    { name: 'hero', title: '🏠 Hero Section' },
    { name: 'welcome', title: '👋 Welcome Section' },
    { name: 'explore', title: '☀️ Explore (Eco & Solar) Section' },
    { name: 'bungalows', title: '🛖 Bungalow Section' },
  ],
  fieldsets: [
    { name: 'hero_en', title: '🇬🇧 English Content', options: { collapsible: true, collapsed: false } },
    { name: 'hero_id', title: '🇮🇩 Indonesian Content', options: { collapsible: true, collapsed: true } },
    { name: 'welcome_en', title: '🇬🇧 English Content', options: { collapsible: true, collapsed: false } },
    { name: 'welcome_id', title: '🇮🇩 Indonesian Content', options: { collapsible: true, collapsed: true } },
    { name: 'explore_en', title: '🇬🇧 English Content', options: { collapsible: true, collapsed: false } },
    { name: 'explore_id', title: '🇮🇩 Indonesian Content', options: { collapsible: true, collapsed: true } },
    { name: 'builtByHand_en', title: '🇬🇧 English Content', options: { collapsible: true, collapsed: false } },
    { name: 'builtByHand_id', title: '🇮🇩 Indonesian Content', options: { collapsible: true, collapsed: true } },
  ],
  fields: [
    // ── Hero Section ──────────────────────────────────
    defineField({
      name: 'heroImage',
      title: 'Hero Background Image',
      description: 'The large background image at the very top of the homepage (high-quality landscape recommended). If removed, the website will use the default image.',
      type: 'image',
      options: { hotspot: true },
      group: 'hero',
    }),
    defineField({
      name: 'heroTitle',
      title: 'Hero Title (English)',
      description: 'Main large heading text over the background image.',
      type: 'string',
      group: 'hero',
      fieldset: 'hero_en',
    }),
    defineField({
      name: 'heroTitle_id',
      title: 'Hero Title (Indonesian)',
      description: 'Judul utama di atas gambar latar belakang.',
      type: 'string',
      group: 'hero',
      fieldset: 'hero_id',
    }),
    defineField({
      name: 'heroSubtitle',
      title: 'Hero Subtitle (English)',
      description: 'Short phrase below the main heading.',
      type: 'string',
      group: 'hero',
      fieldset: 'hero_en',
    }),
    defineField({
      name: 'heroSubtitle_id',
      title: 'Hero Subtitle (Indonesian)',
      description: 'Sub-judul di bawah heading utama.',
      type: 'string',
      group: 'hero',
      fieldset: 'hero_id',
    }),

    // ── Welcome Section ───────────────────────────────
    defineField({
      name: 'welcomeTitle',
      title: 'Welcome Section Title (English)',
      description: 'The heading for the welcome text area.',
      type: 'string',
      group: 'welcome',
      fieldset: 'welcome_en',
    }),
    defineField({
      name: 'welcomeTitle_id',
      title: 'Welcome Section Title (Indonesian)',
      description: 'Judul bagian selamat datang.',
      type: 'string',
      group: 'welcome',
      fieldset: 'welcome_id',
    }),
    defineField({
      name: 'welcomeText',
      title: 'Welcome Section Text (English)',
      description: 'The main introductory paragraphs.',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'welcome',
      fieldset: 'welcome_en',
    }),
    defineField({
      name: 'welcomeText_id',
      title: 'Welcome Section Text (Indonesian)',
      description: 'Paragraf pengantar utama.',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'welcome',
      fieldset: 'welcome_id',
    }),
    defineField({
      name: 'welcomeImage1',
      title: 'Welcome Image 1 (Large Left)',
      description: 'The big image on the left side of the gallery wall. If removed, the website will use the default image.',
      type: 'image',
      options: { hotspot: true },
      group: 'welcome',
    }),
    defineField({
      name: 'welcomeImage2',
      title: 'Welcome Image 2 (Top Right)',
      description: 'The smaller image on the top-right of the gallery wall. If removed, the website will use the default image.',
      type: 'image',
      options: { hotspot: true },
      group: 'welcome',
    }),
    defineField({
      name: 'welcomeImage3',
      title: 'Welcome Image 3 (Bottom Right)',
      description: 'The smaller image on the bottom-right of the gallery wall. If removed, the website will use the default image.',
      type: 'image',
      options: { hotspot: true },
      group: 'welcome',
    }),

    // ── Explore (Built by Hand, Powered by Sun) Section ─────────────────────────
    defineField({
      name: 'exploreTitle',
      title: 'Explore Section Title (English)',
      description: 'Title. e.g., "Built by Hand, Powered by Sun". A responsive line break is automatically added after the comma.',
      type: 'string',
      group: 'explore',
      fieldset: 'explore_en',
    }),
    defineField({
      name: 'exploreTitle_id',
      title: 'Explore Section Title (Indonesian)',
      description: 'Judul. contoh: "Dibangun dengan Tangan, Ditenagai oleh Matahari". Baris baru otomatis ditambahkan setelah tanda koma.',
      type: 'string',
      group: 'explore',
      fieldset: 'explore_id',
    }),
    defineField({
      name: 'exploreContent',
      title: 'Explore Section Content (English)',
      description: 'Paragraphs and blockquotes. Use "Blockquote" style in the editor menu to format quotes. If empty, uses default text.',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'explore',
      fieldset: 'explore_en',
    }),
    defineField({
      name: 'exploreContent_id',
      title: 'Explore Section Content (Indonesian)',
      description: 'Paragraf & kutipan. Pilih format "Blockquote" pada menu atas untuk kutipan. Jika kosong, menggunakan teks bawaan.',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'explore',
      fieldset: 'explore_id',
    }),

    // ── Bungalows Intro Section (formerly Built by Hand fields) ─────────────────────────
    defineField({
      name: 'builtByHandTitle',
      title: 'Bungalows Section Intro Title (English)',
      description: 'Heading shown directly above the bungalow cards. e.g., "Our Floating Bungalows".',
      type: 'string',
      group: 'bungalows',
      fieldset: 'builtByHand_en',
    }),
    defineField({
      name: 'builtByHandTitle_id',
      title: 'Bungalows Section Intro Title (Indonesian)',
      description: 'Judul yang ditampilkan tepat di atas kartu bungalow.',
      type: 'string',
      group: 'bungalows',
      fieldset: 'builtByHand_id',
    }),
    defineField({
      name: 'builtByHandText',
      title: 'Bungalows Section Intro Text (English)',
      description: 'Introductory paragraphs above the bungalow cards.',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'bungalows',
      fieldset: 'builtByHand_en',
    }),
    defineField({
      name: 'builtByHandText_id',
      title: 'Bungalows Section Intro Text (Indonesian)',
      description: 'Paragraf pengantar di atas kartu bungalow.',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'bungalows',
      fieldset: 'builtByHand_id',
    }),

    // ── Bungalow Cards Image Section ──────────────────────────────
    defineField({
      name: 'bungalowImage1',
      title: 'Bungalow Card Image 1 — Sunrise Bungalow',
      description: 'Image shown on the Sunrise Bungalow card on the homepage. If removed, the website will use the default image.',
      type: 'image',
      options: { hotspot: true },
      group: 'bungalows',
    }),
    defineField({
      name: 'bungalowImage2',
      title: 'Bungalow Card Image 2 — Sunset Bungalow',
      description: 'Image shown on the Sunset Bungalow card on the homepage. If removed, the website will use the default image.',
      type: 'image',
      options: { hotspot: true },
      group: 'bungalows',
    }),
    defineField({
      name: 'bungalowImage3',
      title: 'Bungalow Card Image 3 — Bayside Bungalow',
      description: 'Image shown on the Bayside Bungalow card on the homepage. If removed, the website will use the default image.',
      type: 'image',
      options: { hotspot: true },
      group: 'bungalows',
    }),
  ],
})
