import { defineType, defineField } from 'sanity'

export const homepageType = defineType({
  name: 'homepage',
  title: 'Homepage',
  type: 'document',
  groups: [
    { name: 'hero', title: '🏠 Hero Section' },
    { name: 'welcome', title: '👋 Welcome Section' },
    { name: 'bungalows', title: '🛖 Bungalow Section' },
    { name: 'builtByHand', title: '🔨 Built by Hand Section' },
  ],
  fields: [
    // ── Hero Section ──────────────────────────────────
    defineField({
      name: 'heroImage',
      title: 'Hero Background Image',
      description: 'The large background image at the very top of the homepage (high-quality landscape recommended). If removed, the website will use the default image.',
      type: 'image',
      options: { hotspot: true },
      group: 'hero',
    }),
    defineField({
      name: 'heroTitle',
      title: 'Hero Title (English)',
      description: 'Main large heading text over the background image.',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroTitle_id',
      title: 'Hero Title (Indonesian)',
      description: 'Judul utama di atas gambar latar belakang.',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroSubtitle',
      title: 'Hero Subtitle (English)',
      description: 'Short phrase below the main heading.',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroSubtitle_id',
      title: 'Hero Subtitle (Indonesian)',
      description: 'Sub-judul di bawah heading utama.',
      type: 'string',
      group: 'hero',
    }),

    // ── Welcome Section ───────────────────────────────
    defineField({
      name: 'welcomeTitle',
      title: 'Welcome Section Title (English)',
      description: 'The heading for the welcome text area.',
      type: 'string',
      group: 'welcome',
    }),
    defineField({
      name: 'welcomeTitle_id',
      title: 'Welcome Section Title (Indonesian)',
      description: 'Judul bagian selamat datang.',
      type: 'string',
      group: 'welcome',
    }),
    defineField({
      name: 'welcomeText',
      title: 'Welcome Section Text (English)',
      description: 'The main introductory paragraphs.',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'welcome',
    }),
    defineField({
      name: 'welcomeText_id',
      title: 'Welcome Section Text (Indonesian)',
      description: 'Paragraf pengantar utama.',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'welcome',
    }),
    defineField({
      name: 'welcomeImage1',
      title: 'Welcome Image 1 (Large Left)',
      description: 'The big image on the left side of the gallery wall. If removed, the website will use the default image.',
      type: 'image',
      options: { hotspot: true },
      group: 'welcome',
    }),
    defineField({
      name: 'welcomeImage2',
      title: 'Welcome Image 2 (Top Right)',
      description: 'The smaller image on the top-right of the gallery wall. If removed, the website will use the default image.',
      type: 'image',
      options: { hotspot: true },
      group: 'welcome',
    }),
    defineField({
      name: 'welcomeImage3',
      title: 'Welcome Image 3 (Bottom Right)',
      description: 'The smaller image on the bottom-right of the gallery wall. If removed, the website will use the default image.',
      type: 'image',
      options: { hotspot: true },
      group: 'welcome',
    }),

    // ── Built by Hand Section ─────────────────────────
    defineField({
      name: 'builtByHandTitle',
      title: 'Built by Hand Section Title (English)',
      description: 'Heading for the middle storytelling section.',
      type: 'string',
      group: 'builtByHand',
    }),
    defineField({
      name: 'builtByHandTitle_id',
      title: 'Built by Hand Section Title (Indonesian)',
      description: 'Judul untuk bagian cerita di tengah halaman.',
      type: 'string',
      group: 'builtByHand',
    }),
    defineField({
      name: 'builtByHandText',
      title: 'Built by Hand Section Text (English)',
      description: 'Story paragraphs about building Floating Paradise.',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'builtByHand',
    }),
    defineField({
      name: 'builtByHandText_id',
      title: 'Built by Hand Section Text (Indonesian)',
      description: 'Cerita tentang pembangunan Floating Paradise.',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'builtByHand',
    }),

    // ── Bungalow Section ──────────────────────────────
    defineField({
      name: 'bungalowImage1',
      title: 'Bungalow Card Image 1 — Sunrise Bungalow',
      description: 'Image shown on the Sunrise Bungalow card on the homepage. If removed, the website will use the default image.',
      type: 'image',
      options: { hotspot: true },
      group: 'bungalows',
    }),
    defineField({
      name: 'bungalowImage2',
      title: 'Bungalow Card Image 2 — Sunset Bungalow',
      description: 'Image shown on the Sunset Bungalow card on the homepage. If removed, the website will use the default image.',
      type: 'image',
      options: { hotspot: true },
      group: 'bungalows',
    }),
    defineField({
      name: 'bungalowImage3',
      title: 'Bungalow Card Image 3 — Bayside Bungalow',
      description: 'Image shown on the Bayside Bungalow card on the homepage. If removed, the website will use the default image.',
      type: 'image',
      options: { hotspot: true },
      group: 'bungalows',
    }),
  ],
})
